### ISSUE TITLE
Write Up Instructions for Getting Started with Jupyter Books

### ISSUE THREAD

**Issue by cpkrehbiel** [NASA-Openscapes/common#22]
I thought it would be good to share how I got spun up with using Jupyter Books with the group in case anyone else wanted to start adding notebooks, markdown, etc.

**Comment by cpkrehbiel** [comment]
I created a shared doc here: https://docs.google.com/document/d/1kCaPV0BqyLB7_-VnilJ03I8twq62c0J4tykYdH7iB4o/edit?usp=sharing 

Please feel free to review/revise as needed and ask questions!

**Comment by jules32** [comment]
This is so awesome @cpkrehbiel ! I had written [some notes](https://github.com/NASA-Openscapes/openscapes_jupyterbook_test/blob/master/how-to-build-book.md) too but yours are more comprehensive :). 

I've linked your notes from the [Jupyter Book Outline Google Doc](https://docs.google.com/document/d/12uEPP_w4M4SMrLkcVzUwX7htWtTzlS5a3ahJnK7fSAs/edit) too
