### ISSUE TITLE
Pangeo Showcase 15 Min Talk June 30, 12pm ET

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/common#29]
Planning for 15 min talk June 30 at the Pangeo Showcase to share about NASA-Openscapes 

https://pangeo.io/pangeo-showcase.html

Plan: 

- intro to Openscapes - Julie
  - first pass of the flywheel
- intro to NASA-Openscapes - Erin
   - want to reuse existing material, develop mentors who can deliver
   - working on transformation, behavior change
   - take the training and apply it, and don't do that alone  
   - Partners: Carpentries, 2i2c
- intro to EarthData Cloud Cookbook - Erin/Julie
   - co-creation
   - "Carpenterize"
- ask for feedback
  - what does connecting with other groups mean i.e. Project Pythia
  - Carpentries Workshops?

**Comment by jules32** [comment]
Hi @NASA-Openscapes/mentors-2021! 

Next week we're giving a short talk at the Pangeo Community Showcase, and are excited to get feedback from their community. You're all welcome to join and share too: zoom link here: https://pangeo.io/pangeo-showcase.html
We'll put together slides and you're all welcome to contribute too, just let us know :)

**Comment by erinmr** [comment]
I have started some draft [slides here](https://docs.google.com/presentation/d/17XcJSxoE3_-0PqYgQ0l7NctniBNUxaZ5Zo0hjL-bjJo/edit#slide=id.ge13e5189b4_0_863).

**Comment by betolink** [comment]
Your illustrations are on another level @erinmr @jules32 !! looking forward to this presentation

**Comment by jules32** [comment]
Thanks @betolink ! Our illustrations are by the incredible Allison Horst: See https://github.com/allisonhorst/stats-illustrations#hello for more :)

**Comment by cgangoda** [comment]
Hi Julia,
I cannot find the zoom link (https://pangeo.io/pangeo-showcase.html
) for the Pangeo Community Showcase talk.
Would you please forward that to me?
Thank you.
Chandana


From: Julia Stewart Lowndes ***@***.***>
Reply-To: NASA-Openscapes/common ***@***.***>
Date: Friday, June 25, 2021 at 5:56 PM
To: NASA-Openscapes/common ***@***.***>
Cc: "GANGODAGAMAGE, CHANDANA (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Team mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-Openscapes/common] Pangeo Showcase 15 Min Talk June 30, 12pm ET (#29)


Hi @NASA-Openscapes/mentors-2021<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2FNASA-Openscapes%2Fteams%2Fmentors-2021&data=04%7C01%7Cchandana.gangodagamage%40nasa.gov%7C6e26a69b39ca449a964208d938240d9b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637602549768876259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N0MRhP9bjwu37mKS3RFwk02TRgaNIkyxlDt%2BmD%2FP4xw%3D&reserved=0>!

Next week we're giving a short talk at the Pangeo Community Showcase, and are excited to get feedback from their community. You're all welcome to join and share too: zoom link here: https://pangeo.io/pangeo-showcase.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpangeo.io%2Fpangeo-showcase.html&data=04%7C01%7Cchandana.gangodagamage%40nasa.gov%7C6e26a69b39ca449a964208d938240d9b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637602549768886214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WjvzgKMCC0vWZI7ikqpkGSfk60xH51%2BPh%2BZAn7HnuQQ%3D&reserved=0>
We'll put together slides and you're all welcome to contribute too, just let us know :)

**Comment by erinmr** [comment]
So sorry that I'm just seeing this now, @cgangoda. Their zoom details are separate from the announcement page, but the talk was recorded and we'll add to this thread
